name: Changelog
on:
  pull_request:
    types: [closed]
  release:
    types: [published]
  issues:
    types: [closed, edited]
  push:
    branches: [master]
    tags:
      - v*
jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: Generate changelog for master branch
    steps:
      - uses: actions/checkout@v2
      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: changelog.md
          set-safe-directory: '/github/workspace'
      - name: push
        uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'auto update changelog'
          force-add: 'true'
          files: changelog.md
          name: dev-sec CI
          email: mauricio@gofas.net
